#!/bin/bash
sudo apt-get update
sudo apt-get install cron

#write out current crontab
crontab -l > mycron
#echo new cron into cron file
echo "* * * * * echo ‘Run this command every minute’ >> /home/nuran/file.log " >> mycron
#install new cron file
crontab mycron
rm mycron
